version: 2
updates:
  # Keep npm dependencies up to date
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    # Group all updates together
    groups:
      dependencies:
        patterns:
          - '*'

  # Keep GitHub Actions up to date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      github-actions:
        patterns:
          - '*'

  # Keep Docker dependencies up to date
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'
